server:
  port: 80
  servlet:
    context-path: /audit
spring:
  datasource:
    name: datasource
    url: jdbc:mysql://localhost:3306/dev?serverTimezone=GMT%2B8&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    max-active: 2
    max-idle: 2
    min-idle: 2
    initial-size: 2
    validation-query: select 1
    test-on-borrow: true
    test-on-return: false
    test-while-idle: false
    time-between-eviction-runs-millis: 3000
    min-evictable-idle-time-millis: 3000
    max-wait: 3000
    jmx-enabled: true
  data:
    jpa:
      repository:
      enabled: true
mybatis:
  type-aliases-package: com.mimeo.audit.model
  mapper-locations: classpath*:/mapper/**.xml